import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

const redirectEntries = [
  ['/filosofia.html', '/il-centro/'], ['/attivita-servizi.html', '/servizi/'], ['/orari.html', '/orari/'], ['/orari_corsi.html', '/orari/'], ['/contatti.html', '/contatti/'], ['/bus.html', '/contatti/'], ['/gallery/gallery.html', '/gallery/'], ['/specialisti.html', '/specialisti/'], ['/tshirt.html', '/'], ['/sport_test/sport_test.html', '/servizi/preparazione-atletica/'], ['/yoga.html', '/servizi/ginnastica-posturale/'], ['/sport.html', '/servizi/preparazione-atletica/'], ['/tennis/tennis.html', '/servizi/preparazione-atletica/'], ['/news/index.html', '/servizi/'], ['/news/attivita-servizi.html', '/servizi/'], ['/news/prog_spec_ind.html', '/servizi/'], ['/news/ried_respiratoria.html', '/servizi/rieducazione-respiratoria/'],
  ['/prep_atletica_sport.html', '/servizi/preparazione-atletica/'], ['/rieducazione.html', '/servizi/rieducazione-funzionale/'], ['/rieducazione_funzionale.html', '/servizi/rieducazione-funzionale/'], ['/palestra.html', '/servizi/palestra/'], ['/area_fitness.html', '/servizi/palestra/'], ['/cardio_aerobico.html', '/servizi/cardiofitness/'], ['/circuit_training.html', '/servizi/circuit-training/'], ['/hiit.html', '/servizi/hiit/'], ['/programmi_dimagrimento.html', '/servizi/programmi-dimagrimento/'], ['/core_stability.html', '/servizi/core-stability/'], ['/rinforzo_schiena.html', '/servizi/rinforzo-schiena/'], ['/ginn_posturale.html', '/servizi/ginnastica-posturale/'], ['/ginn_posturale_ind.html', '/servizi/ginnastica-posturale-individuale/'], ['/scoliosi_lordosi_cifosi.html', '/servizi/scoliosi-lordosi-cifosi/'], ['/ginn_correttiva.html', '/servizi/ginnastica-correttiva-ragazzi/'], ['/ginn_dolce.html', '/servizi/ginnastica-dolce/'], ['/ginn_dolce_ind.html', '/servizi/ginnastica-dolce-individuale/'], ['/ginn_terza_eta.html', '/servizi/ginnastica-terza-eta/'], ['/ried_respiratoria.html', '/servizi/rieducazione-respiratoria/'], ['/panca_fit.html', '/servizi/pancafit/'], ['/metodologia_pancafit_adattata.html', '/servizi/pancafit/'], ['/stretching.html', '/servizi/pancafit/'], ['/functional_training.html', '/servizi/functional-training/'], ['/trx.html', '/servizi/functional-training/'], ['/trx_corsi.html', '/servizi/functional-training/'], ['/news/trx.html', '/servizi/functional-training/'],
  ['/prep_individuale.html', '/servizi/preparazione-individuale/'], ['/prep_squadre.html', '/servizi/preparazione-squadre/'], ['/volley/volley.html', '/servizi/preparazione-squadre/'], ['/golf/golf.html', '/servizi/golf/'], ['/sci/sci.html', '/servizi/sci/'], ['/snowboard/snowboard.html', '/servizi/sci/'], ['/running/running.html', '/servizi/running/'], ['/pallacanestro/pallacanestro.html', '/servizi/basket/'], ['/calcio/calcio.html', '/servizi/calcio/'], ['/kite_wind_surf.html', '/servizi/surf-kite-wind/'], ['/news/hockey_slideboard.html', '/servizi/hockey-slide-board/'],
  ['/fisioterapista.html', '/servizi/fisioterapia-riabilitazione/'], ['/massofisioterapista.html', '/servizi/massofisioterapia/'], ['/osteopata.html', '/servizi/osteopatia/'], ['/preparatore_atletico.html', '/specialisti/'], ['/medico.html', '/servizi/medico-sportivo/'], ['/nutrizionista.html', '/servizi/nutrizionista-dietologa/'], ['/dietologa_nutrizionista.html', '/servizi/nutrizionista-dietologa/'], ['/infortunio/infortunio.html', '/servizi/riatletizzazione/'], ['/post_trauma-infortunio.html', '/servizi/riatletizzazione/'], ['/rieducazione_prep.html', '/servizi/riatletizzazione/'], ['/propriocettiva.html', '/servizi/ginnastica-propriocettiva/'], ['/ginnastica_propriocettiva.html', '/servizi/ginnastica-propriocettiva/'], ['/ritorno_in_campo/ritorno_in_campo.html', '/servizi/ritorno-in-campo/'], ['/preparazione_intervento.html', '/servizi/preparazione-pre-intervento/'], ['/pilates.html', '/servizi/pilates/'], ['/pilatesEN.html', '/en/pilates/'], ['/presciistica.html', '/servizi/presciistica/'], ['/news/powerbreatheplus.html', '/servizi/powerbreathe-plus/'],
  ['/partner_jolly_sport.html', '/partner/#jolly-sport'], ['/partner_olt.html', '/partner/#olt-ortopedia'], ['/partner_enervit.html', '/partner/#enervit'], ['/partner_balon_boys.html', '/partner/#balon-boys'], ['/partner_eqb.html', '/partner/#eqb'], ['/partner_turin_tour.html', '/partner/#turin-tour'], ['/partner_adidas.html', '/partner/#adidas'], ['/partner_fnac.html', '/partner/#fnac'],
  ['/indexEN.html', '/en/'], ['/mission.html', '/en/mission/'], ['/services.html', '/en/services/'], ['/opening_hours.html', '/en/opening-hours/'], ['/contact_us.html', '/en/contact/'], ['/classes_hrs.html', '/en/opening-hours/'], ['/busEN.html', '/en/contact/'], ['/partner_jolly_sportEN.html', '/en/services/'], ['/partner_adidasEN.html', '/en/services/'], ['/partner_enervitEN.html', '/en/services/'], ['/partner_balon_boysEN.html', '/en/services/'], ['/partner_eqbEN.html', '/en/services/']
];

export default defineConfig({
  site: 'https://www.lajolla.it',
  integrations: [sitemap()],
  output: 'static',
  redirects: Object.fromEntries(redirectEntries)
});
